Update included dj-setup-database script to latest version and fix it to use passwords from dbconfig-common.

diff --git a/live-usb/files/usr/local/bin/dj-setup-database b/live-usb/files/usr/local/bin/dj-setup-database
--- a/live-usb/files/usr/local/bin/dj-setup-database
+++ b/live-usb/files/usr/local/bin/dj-setup-database
@@ -1,6 +1,5 @@
 #!/bin/sh
-# Generated from 'dj-setup-database.in' on Sun Dec 11 11:31:29 CET 2011.
-# $Id: dj-setup-database.in 3726 2011-11-09 13:39:05Z kink $
+# Generated from 'dj-setup-database.in' on Thu Jun 27 21:05:04 BST 2013.
 
 # This script allows one to perform DOMjudge database setup actions.
 # See usage below for possible commands and options.
@@ -10,11 +9,14 @@ set -e
 ETCDIR="/etc/domjudge"
 SQLDIR="/usr/share/domjudge/sql"
 
-PASSWDFILE="$ETCDIR/dbpasswords.secret"
+PASSWDFILE="/etc/dbconfig-common/domjudge-domserver.conf"
 
-ROLES='jury team public plugin'
+verbose()
+{
+	[ -z "$QUIET" ] && echo "$@"
+}
 
-# Wrapper around mysql command to allow settings options, user, etc.
+# Wrapper around mysql command to allow setting options, user, etc.
 mysql()
 {
 	local user pass
@@ -30,38 +32,43 @@ mysql()
 		[ -n "$PROMPT_PASSWD" ] && pass="-p"
 		[ -n "$DBA_PASSWD" ]    && pass="-p$DBA_PASSWD"
 	fi
-	command mysql $user $pass -h $DBHOST --silent --skip-column-names "$@"
+	command mysql --defaults-file=/etc/mysql/debian.cnf $user $pass \
+		-h $DBHOST --silent --skip-column-names "$@"
 }
 
+# This function is modified from the original to read passwords from
+# the Debian dbconfig-common settings.
 read_dbpasswords()
 {
-	local OLDIFS="$IFS"
-	IFS=":"
-	# Don't pipe $PASSWDFILE into this while loop as that spawns a
-	# subshell and then variables are not retained in the original shell.
-	while read role host db user passwd; do
-		# Skip lines beginning with a '#'
-		[ "x$role" != "x${role###}" ] && continue
-		eval "${role}_DBHOST=$host"
-		eval "${role}_DBNAME=$db"
-		eval "${role}_DBUSER=$user"
-		eval "${role}_PASSWD=$passwd"
-		if [ "x$role" = xjury ]; then
-			DBHOST=$host
-			DBNAME=$db
-		fi
-	done < "$PASSWDFILE"
-	IFS="$OLDIFS"
-	if [ -z "$jury_PASSWD" -o -z "$team_PASSWD" -o -z "$public_PASSWD" ]; then
-		echo "Error: no login info found for one of jury, team, public users."
+	if [ ! -r "$PASSWDFILE" ]; then
+		echo "Error: password file '$PASSWDFILE' not found or not readable."
 		return 1
 	fi
+
+# We can simply source the configuration file, since it is valid shell
+# script that only contains variable definitions that do not clash.
+
+	. $PASSWDFILE
+
+	domjudge_DBHOST=${dbc_dbserver:-localhost}
+	domjudge_DBNAME=$dbc_dbname
+	domjudge_DBUSER=$dbc_dbuser
+	domjudge_PASSWD=$dbc_dbpass
+
+	DBHOST=$domjudge_DBHOST
+	DBNAME=$domjudge_DBNAME
+
+	if [ -z "$domjudge_PASSWD" ]; then
+		echo "Error: no login info found."
+		return 1
+	fi
+	verbose "Database credentials read from '$PASSWDFILE'."
 }
 
 status()
 {
 	if [ ! -r "$PASSWDFILE" ]; then
-		echo "Error: cannot read database passwords file '$PASSWDFILE'."
+		echo "Error: cannot read database password file '$PASSWDFILE'."
 		return 1
 	fi
 	read_dbpasswords || return 1
@@ -69,19 +76,15 @@ status()
 	echo -n "Trying to connect to the server as DB admin: "
 	mysql -e 'SELECT "success.";' || return 1
 
-	for role in $ROLES ; do
-		eval "user=\$${role}_DBUSER"
-		eval "pass=\$${role}_PASSWD"
-		echo -n "Trying to connect to the server with role '$role': "
-		DBUSER=$user PASSWD=$pass mysql -e 'SELECT "success.";' || return 1
-	done
+	echo -n "Trying to connect to the server with user '$domjudge_DBUSER': "
+	DBUSER=$domjudge_DBUSER PASSWD=$domjudge_PASSWD mysql -e 'SELECT "success.";' || return 1
 
 	echo -n "Searching for database \`$DBNAME\`: "
 	mysql -e "USE \`$DBNAME\`; SELECT 'found.';" || return 1
 
 	echo -n "Searching for data in database: "
-	DBUSER=$jury_DBUSER PASSWD=$jury_PASSWD \
-		mysql -e "USE \`$DBNAME\`; SELECT name FROM problem WHERE probid = 'hello';" || return 1
+	DBUSER=$domjudge_DBUSER PASSWD=$domjudge_PASSWD \
+		mysql -e "USE \`$DBNAME\`; SELECT name FROM team WHERE login = 'domjudge';" || return 1
 
 	echo -n "MySQL server version: "
 	mysql -e 'SELECT version();'
@@ -92,18 +95,18 @@ create_db_users()
 	local user pass
 	(
 	echo "CREATE DATABASE \`$DBNAME\` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;"
-	for role in $ROLES ; do
-		eval "user=\$${role}_DBUSER"
-		eval "pass=\$${role}_PASSWD"
 # Need to add both '%' and 'localhost' as entries, because a default
 # fresh MySQL installation has a Host='localhost',User='' entry which
 # is more specific than Host='%' and thus leads to Access Denied errors.
-		echo "CREATE USER
-			'$user'@'%' IDENTIFIED BY '$pass',
-			'$user'@'localhost' IDENTIFIED BY '$pass';"
-	done
+	echo "CREATE USER
+		'$domjudge_DBUSER'@'%' IDENTIFIED BY '$domjudge_PASSWD',
+		'$domjudge_DBUSER'@'localhost' IDENTIFIED BY '$domjudge_PASSWD';"
+
+	echo "GRANT SELECT, INSERT, UPDATE, DELETE ON \`$DBNAME\`.* TO '$domjudge_DBUSER';"
+
 	echo "FLUSH PRIVILEGES;"
 	) | mysql
+	verbose "DOMjudge database and user(s) created."
 }
 
 remove_db_users()
@@ -111,28 +114,29 @@ remove_db_users()
 	local user pass
 	(
 	echo "DROP DATABASE IF EXISTS \`$DBNAME\`;"
-	for role in $ROLES ; do
-		eval "user=\$${role}_DBUSER"
 # In MySQL < 5.0.2, 'DROP USER' only removes the user, not its privileges:
-		echo "REVOKE ALL PRIVILEGES, GRANT OPTION FROM
-			'$user'@'%', '$user'@'localhost';"
-		echo "DROP USER
-			'$user'@'%', '$user'@'localhost';"
-	done
+	echo "REVOKE ALL PRIVILEGES, GRANT OPTION FROM
+		'$domjudge_DBUSER'@'%', '$domjudge_DBUSER'@'localhost';"
+	echo "DROP USER
+		'$domjudge_DBUSER'@'%', '$domjudge_DBUSER'@'localhost';"
 	echo "FLUSH PRIVILEGES;"
 	) | mysql -f
+	verbose "DOMjudge database and user(s) removed."
 }
 
 ### Script starts here ###
 
 # Parse command-line options:
-while getopts ':u:p:r' OPT ; do
+while getopts ':u:p:qr' OPT ; do
 	case "$OPT" in
 		u)
 			DBA_USER=$OPTARG
 			;;
 		p)
 			DBA_PASSWD=$OPTARG
+			;;
+		q)
+			QUIET=1
 			;;
 		r)
 			PROMPT_PASSWD=1
@@ -172,21 +176,27 @@ genpass)
 	fi
 	echo "Running '$ETCDIR/gendbpasswords'..."
 	$ETCDIR/gendbpasswords > "$PASSWDFILE"
-	echo "Passwords file '$PASSWDFILE' created."
+	echo "Password file '$PASSWDFILE' created."
 	;;
 
 install)
 	read_dbpasswords
 	create_db_users
-	TMPFILE=`mktemp /tmp/domjudge-sql.XXXXXX`
-	cp $SQLDIR/mysql_privileges.sql $TMPFILE
-	for role in $ROLES ; do
-		eval "user=\$${role}_DBUSER"
-		sed -i -e "s/domjudge_$role/$user/g" $TMPFILE
-	done
+	cat $SQLDIR/mysql_db_structure.sql \
+	    $SQLDIR/mysql_db_defaultdata.sql \
+	    $SQLDIR/mysql_db_examples.sql \
+	     | mysql -D "$DBNAME"
+	verbose "SQL structure and default/example data installed."
+	rm -f $TMPFILE
+	;;
+
+bare-install)
+	read_dbpasswords
+	create_db_users
  	cat $SQLDIR/mysql_db_structure.sql \
- 	    $SQLDIR/mysql_db_examples.sql \
-	    $TMPFILE | mysql -D "$DBNAME"
+ 	    $SQLDIR/mysql_db_defaultdata.sql \
+	     | mysql -D "$DBNAME"
+	verbose "SQL structure and defaults installed(No sample data)."
 	rm -f $TMPFILE
 	;;
 
@@ -198,24 +208,23 @@ uninstall)
 # Upgrades the DB structure and permissions to current version
 # using SQL upgrade files under sql/upgrade.
 upgrade)
-	TMPOUT=`mktemp /tmp/domjudge-sql.XXXXXX`
-	TMPSQL=`mktemp /tmp/domjudge-sql.XXXXXX`
+	# check for legacy dbpasswords.secret content
+	if grep -Eq ^team: $PASSWDFILE >/dev/null 2>&1 ; then
+		echo "Warning: please remove all non-jury users from $PASSWDFILE"
+		echo "You may also remove those users from MySQL."
+	fi
+	TMPOUT=`mktemp --tmpdir domjudge-sql.XXXXXX`
 	read_dbpasswords
-	for i in "$SQLDIR"/upgrade/* ; do
+	for i in "$SQLDIR"/upgrade/*.sql ; do
 		if [ ! -r "$i" ]; then
 			echo "Error: cannot read upgrade script '$i'."
 			exit 1
 		fi
-		cp "$i" $TMPSQL
-		for role in $ROLES ; do
-			eval "user=\$${role}_DBUSER"
-			sed -i -e "s/domjudge_$role/$user/g" $TMPSQL
-		done
 		# First find the line where the upgrade check is performed to
 		# filter possible error messages later.
 		UPGRADELINE=`grep -n '@UPGRADE-CHECK@' "$i" | cut -d : -f 1`
 		UPGRADELINE=$((UPGRADELINE+1))
-		if cat $TMPSQL | mysql -D "$DBNAME" >$TMPOUT 2>&1 ; then
+		if cat $i | mysql -D "$DBNAME" >$TMPOUT 2>&1 ; then
 			echo "Upgraded script '$i'."
 		else
 			if grep -E "^ERROR .* at line ${UPGRADELINE}: " $TMPOUT >/dev/null 2>&1 ; then
@@ -223,12 +232,13 @@ upgrade)
 			else
 				echo "Error upgrading script '$i':"
 				cat $TMPOUT
-				rm -f $TMPOUT $TMPSQL
+				rm -f $TMPOUT
 				exit 1
 			fi
 		fi
 	done
-	rm -f $TMPOUT $TMPSQL
+	verbose "DOMjudge database upgrade completed."
+	rm -f $TMPOUT
 	;;
 
 	*)
@@ -237,16 +247,20 @@ Unknown subcommand '$1'
 Usage: $0 [option]... <command>
 
 Commands:
-  status     check database installation status
-  genpass    generate passwords
-  install    create database, contents and users if not existing
-  uninstall  remove database users and database, INCLUDING ALL DATA!
-  upgrade    upgrade MySQL database schema to current version
+  status        check database installation status
+  genpass       generate password file
+  install       create database, example contest and users if not existing
+  bare-install  create database, setup defaults if not existing
+  uninstall     remove database users and database, INCLUDING ALL DATA!
+  upgrade       upgrade MySQL database schema to current version
 
 Options:
   -u <user>  connect to MySQL with DB admin <user>
   -p <pass>  use password <pass> for DB admin user
   -r         read DB admin password from prompt
+
+Note that by default this script will use the Debian system
+maintenance credentials for accessing the MySQL database.
 
 EOF
 	exit 1
